name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HEASARC_CHANNEL: "https://heasarc.gsfc.nasa.gov/FTP/software/conda"

jobs:
  cache:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Cache Xspec Conda Package (Linux-x64)
            os: "ubuntu-latest"

          - name: Cache Xspec Conda Package (macOS-arm64)
            os: "macos-latest"
    outputs:
      xspec-fn: ${{ steps.package-info.outputs.xspec-fn }}
      data-fn: ${{ steps.package-info.outputs.data-fn }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Get Latest Version of Xspec Conda Package
        id: package-info
        run: |
          get_latest_pkg() {
            jq '
              .result.pkgs
              | sort_by(
                  (
                    .version
                    | capture("^(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?(?<suffix>[a-z]*)?")
                    | {
                        major: (.major | tonumber),
                        minor: (.minor // "0" | tonumber),
                        patch: (.patch // "0" | tonumber),
                        suffix: .suffix
                      }
                  ) + { build: .build_number }
                  | [ .major, .minor, .patch, .suffix, .build ]
                )
              | .[-1]
            '
          }

          pkg_dir=$(conda info --json | jq -r '.pkgs_dirs[0]')
          echo "CONDA_PKG_DIR=$pkg_dir" >> "$GITHUB_ENV"

          xspec_pkg=$(mamba search xspec -c $HEASARC_CHANNEL --json | get_latest_pkg)
          xspec_version=$(echo $xspec_pkg | jq -r '.version')
          xspec_build=$(echo $xspec_pkg | jq -r '.build_string')
          xspec_url=$(echo $xspec_pkg | jq -r '.url')
          xspec_fn=$(echo $xspec_pkg | jq -r '.fn')
          echo "XSPEC_VERSION=$xspec_version" >> "$GITHUB_ENV"
          echo "XSPEC_BUILD=$xspec_build" >> "$GITHUB_ENV"
          echo "XSPEC_URL=$xspec_url" >> "$GITHUB_ENV"
          echo "XSPEC_FN=$xspec_fn" >> "$GITHUB_ENV"
          echo "xspec-fn=$xspec_fn" >> "$GITHUB_OUTPUT"

          data_pkg=$(mamba search xspec-data -c $HEASARC_CHANNEL --json | get_latest_pkg)
          data_version=$(echo $data_pkg | jq -r '.version')
          data_build=$(echo $data_pkg | jq -r '.build_string')
          data_url=$(echo $data_pkg | jq -r '.url')
          data_fn=$(echo $data_pkg | jq -r '.fn')
          echo "DATA_VERSION=$data_version" >> "$GITHUB_ENV"
          echo "DATA_BUILD=$data_build" >> "$GITHUB_ENV"
          echo "DATA_URL=$data_url" >> "$GITHUB_ENV"
          echo "DATA_FN=$data_fn" >> "$GITHUB_ENV"
          echo "data-fn=$data_fn" >> "$GITHUB_OUTPUT"

      - name: Cache Xspec ${{ env.XSPEC_VERSION }} (Build ${{ env.XSPEC_BUILD }})
        id: cache-xspec
        uses: actions/cache@v4
        with:
          path: "${{ env.CONDA_PKG_DIR }}/${{ env.XSPEC_FN }}"
          key: "${{ runner.os }}-${{ env.XSPEC_FN }}"
          lookup-only: true

      - name: Cache Xspec Model Data ${{ env.DATA_VERSION }} (Build ${{ env.DATA_BUILD }})
        id: cache-xspec-model-data
        uses: actions/cache@v4
        with:
          path: "${{ env.CONDA_PKG_DIR }}/${{ env.DATA_FN }}"
          key: "${{ env.DATA_FN }}"
          lookup-only: true

      - name: Download Xspec ${{ env.XSPEC_VERSION }} (Build ${{ env.XSPEC_BUILD }})
        if: steps.cache-xspec.outputs.cache-hit != 'true'
        run: |
          aria2c -x 16 -s 16 --show-console-readout=true "$XSPEC_URL"
          if [ ! -f "$XSPEC_FN" ]; then
            echo "Failed to download from $XSPEC_URL"
            exit 1  # Exit with a non-zero status to fail the job
          fi

      - name: Download Xspec Model Data ${{ env.DATA_VERSION }} (Build ${{ env.DATA_BUILD }})
        if: runner.os == 'Linux' && steps.cache-xspec-model-data.outputs.cache-hit != 'true'
        run: |
          aria2c -x 16 -s 16 --show-console-readout=true "$DATA_URL"
          if [ ! -f "$DATA_FN" ]; then
            echo "Failed to download from $DATA_URL"
            exit 1  # Exit with a non-zero status to fail the job
          fi

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: cache
    strategy:
      matrix:
        include:
          - name: Tests (Python 3.13 in Linux-x64)
            os: "ubuntu-latest"
            python-version: "3.13"
            uv-resolution: "highest"

          - name: Tests (Python 3.13 in macOS-arm64)
            os: "macos-latest"
            python-version: "3.13"
            uv-resolution: "highest"

          - name: Tests (Lowest Version Deps)
            os: "ubuntu-latest"
            python-version: "3.9"
            uv-resolution: "lowest-direct"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Get Conda Package Path
        run: |
          pkg_dir=$(conda info --json | jq -r '.pkgs_dirs[0]')
          echo "CONDA_PKG_DIR=$pkg_dir" >> "$GITHUB_ENV"

      - name: Cache Xspec
        uses: actions/cache@v4
        with:
          path: "${{ env.CONDA_PKG_DIR }}/${{ needs.cache.outputs.xspec-fn }}"
          key: "${{ runner.os }}-${{ needs.cache.outputs.xspec-fn }}"
          fail-on-cache-miss: true

      - name: Cache Xspec Model Data
        uses: actions/cache@v4
        with:
          path: "${{ env.CONDA_PKG_DIR }}/${{ needs.cache.outputs.data-fn }}"
          key: "${{ runner.os }}-${{ needs.cache.outputs.data-fn }}"
          fail-on-cache-miss: true

      - name: Install Xspec
        run: |
          mamba install xspec xspec-data -c $HEASARC_CHANNEL -c conda-forge -y

      - name: Install Python Dependencies
        run: |
          uv pip compile pyproject.toml \
            --output-file requirements.txt \
            --resolution ${{ matrix.uv-resolution }}
          uv pip install -e ".[test]" --overrides requirements.txt --verbose

      - name: Run Tests
        run: |
          pytest

      - name: Upload Test Results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          file: junit.xml
          flags: "py${{ matrix.python-version }}"
          name: "Python ${{ matrix.python-version }}"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload Coverage Results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    needs: cache
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: "3.13"

      - name: Get Conda Package Path
        run: |
          pkg_dir=$(conda info --json | jq -r '.pkgs_dirs[0]')
          echo "CONDA_PKG_DIR=$pkg_dir" >> "$GITHUB_ENV"

      - name: Cache Xspec
        uses: actions/cache@v4
        with:
          path: "${{ env.CONDA_PKG_DIR }}/${{ needs.cache.outputs.xspec-fn }}"
          key: "${{ runner.os }}-${{ needs.cache.outputs.xspec-fn }}"
          fail-on-cache-miss: true

      - name: Install Xspec
        run: |
          mamba install xspec -c $HEASARC_CHANNEL -c conda-forge -y

      - name: Install Python Dependencies
        run: |
          pip install -U build twine

      - name: Build and Check Source Distribution
        run: |
          python -m build --sdist .
          python -m twine check --strict dist/*

      - name: Upload Source Distribution as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xspex
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [tests, build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment:
      name: PyPI
      url: https://pypi.org/p/xspex
    permissions:
      id-token: write
    steps:
      - name: Download Source Distribution
        uses: actions/download-artifact@v4
        with:
          name: xspex
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
