name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HEASARC_CHANNEL: "https://heasarc.gsfc.nasa.gov/FTP/software/conda"

jobs:
  download:
    name: Cache XSPEC Model Data
    runs-on: ubuntu-latest
    outputs:
      data-fn: ${{ steps.get_info.outputs.fn }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Install Utils
        run: |
          sudo apt-get install -y aria2 jq

      - name: Get Latest Version of XSPEC Model Data
        id: get_info
        run: |
          get_latest_pkg() {
            jq '
              .result.pkgs
              | sort_by(
                  (
                    .version
                    | capture("^(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?(?<suffix>[a-z]*)?")
                    | {
                        major: (.major | tonumber),
                        minor: (.minor // "0" | tonumber),
                        patch: (.patch // "0" | tonumber),
                        suffix: .suffix
                      }
                  ) + { build: .build_number }
                  | [ .major, .minor, .patch, .suffix, .build ]
                )
              | .[-1]
            '
          }

          data_pkg=$(mamba search xspec-data -c $HEASARC_CHANNEL --json | get_latest_pkg)
          version=$(echo $data_pkg | jq -r '.version')
          build=$(echo $data_pkg | jq -r '.build_string')
          url=$(echo $data_pkg | jq -r '.url')
          fn=$(echo $data_pkg | jq -r '.fn')
          echo "VERSION=$version" >> "$GITHUB_ENV"
          echo "BUILD=$build" >> "$GITHUB_ENV"
          echo "URL=$url" >> "$GITHUB_ENV"
          echo "FN=$fn" >> "$GITHUB_ENV"
          echo "fn=$fn" >> "$GITHUB_OUTPUT"

      - name: Cache XSPEC Model Data ${{ env.VERSION }} (Build ${{ env.BUILD }})
        id: cache-xspec-model-data
        uses: actions/cache@v4
        with:
          path: ${{ env.FN }}
          key: ${{ env.FN }}
          lookup-only: true

      - name: Download XSPEC Model Data ${{ env.VERSION }} (Build ${{ env.BUILD }})
        if: steps.cache-xspec-model-data.outputs.cache-hit != 'true'
        run: |
          aria2c -x 16 -s 16 --show-console-readout=true "$URL"
          if [ ! -f "$FN" ]; then
            echo "Failed to download from $URL"
            exit 1  # Exit with a non-zero status to fail the job
          fi

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: download
    strategy:
      matrix:
        include:
          - name: Tests (Python 3.13 on Linux-x64)
            os: "ubuntu-latest"
            python-version: "3.13"
            uv-resolution: "highest"
            parallel_cpu: "1"

          - name: Tests (Python 3.13 on macOS-arm64)
            os: "macos-latest"
            python-version: "3.13"
            uv-resolution: "highest"
            parallel_cpu: "1"

          - name: Tests (Lowest Version Deps)
            os: "ubuntu-latest"
            python-version: "3.10"
            uv-resolution: "lowest-direct"
            parallel_cpu: "1"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache XSPEC Model Data
        uses: actions/cache@v4
        with:
          path: ${{ needs.download.outputs.data-fn }}
          key: ${{ needs.download.outputs.data-fn }}
          fail-on-cache-miss: true

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install XSPEC
        run: |
          mamba install xspec -c $HEASARC_CHANNEL -c conda-forge -y
          conda install --use-local ${{ needs.download.outputs.data-fn }} -y

      - name: Install Python Dependencies
        run: |
          uv pip compile pyproject.toml \
            --output-file requirements.txt \
            --resolution ${{ matrix.uv-resolution }}
          # Ensure build and runtime deps match
          uv pip install ".[test]" \
            --overrides requirements.txt \
            --build-constraint requirements.txt \
            --verbose

      - name: Run Tests
        run: |
          pytest -n ${{ matrix.parallel_cpu }}

      - name: Upload Test Results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          file: junit.xml
          flags: "py${{ matrix.python-version }}"
          name: "Python ${{ matrix.python-version }}"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload Coverage Results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: "3.13"

      - name: Install XSPEC
        run: |
          mamba install xspec -c $HEASARC_CHANNEL -c conda-forge -y

      - name: Install Python Dependencies
        run: |
          pip install -U build twine

      - name: Build and Check Source Distribution
        run: |
          python -m build --sdist .
          python -m twine check --strict dist/*

      - name: Upload Source Distribution as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xspex
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [ tests, build ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment:
      name: PyPI
      url: https://pypi.org/p/xspex
    permissions:
      id-token: write
    steps:
      - name: Download Source Distribution
        uses: actions/download-artifact@v5
        with:
          name: xspex
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
